name: Lint
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
      - name: run linting
        id: lint_long
        run: |
          make lint
