name: "Checks dependencies"
on:
  merge_group:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ci-${{ github.ref }}-pr-go-mod-tidy
  cancel-in-progress: true

jobs:
  go-mod-tidy:
    name: Check go mod tidy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"
          check-latest: true
      - name: Run go mod tidy
        run: ./scripts/go-mod-tidy-all.sh
      - name: Check for diffs
        run: |
          git diff --exit-code || {
            echo "Please run './scripts/go-mod-tidy-all.sh' and commit the changes";
            exit 1;
          }
