name: Sims Nightly (Long)
# Release Sims workflow runs long-lived (multi-seed & large block size) simulations
on:
  schedule:
    - cron: "0 8 * * *"
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-sims-nightly-long
  cancel-in-progress: true

jobs:
  test-sim-multi-seed-long:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
      - name: test-sim-multi-seed-long
        env:
          GOMEMLIMIT: 14GiB # reserve 2 GiB as buffer for GC to avoid OOM
        run: |
          make test-sim-multi-seed-long
