name: v2 Core Tests
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}-v2-tests
  cancel-in-progress: true

jobs:
  runtime-v2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: test
        run: |
          cd runtime/v2 && go test -mod=readonly -race -timeout 30m

  server-v2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: test
        run: |
          cd server/v2 && go test -mod=readonly -race -timeout 30m

  stf:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: test
        run: |
          cd server/v2/stf && go test -mod=readonly -race -timeout 30m

  appmanager:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: test
        run: |
          cd server/v2/appmanager && go test -mod=readonly -race -timeout 30m

  cometbft:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: test
        run: |
          cd server/v2/cometbft && go test -mod=readonly -race -timeout 30m

  store-v2:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: true
          cache-dependency-path: go.sum
      - name: test
        run: |
          cd store/v2 && go test -mod=readonly -race -timeout 30m

  test-system-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - uses: actions/setup-go@v5
        with:
          go-version: "stable"
          check-latest: true
          cache: true
          cache-dependency-path: |
            simapp/v2/go.sum
      - name: Install musl lib for simd (docker) binary
        run: |
          sudo apt-get install -y musl
      - name: system tests v2
        run: |
          make test-system
